In [1]:
!pip install nltk
!pip install seaborn
!pip install matplotlib
import pandas as pd
import nltk
import seaborn as sea
import matplotlib as plt

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.23.5)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.47.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.47.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [2]:
#read the data
data = pd.read_excel('/content/Input Data.xlsx')
data

,id,Product_id,Product_flavor_id,Shopper_id,User_id,Orderitem_id,description,images,rating,rating_reason,reply,status,date_create,date_modify,LLM
0,47854,4504,10684,3583190052525640192,1000253,663560,The phone looks great. 10/10 quality. Delivere...,[],5,Delayed Delivery,NaN,1,2023-06-10 16:41:38,2023-06-12 09:42:35,positive\n
1,47856,5879,12207,1882191115889570048,1000253,664030,Thank you,[],5,Product Quality,NaN,1,2023-06-10 18:00:06,2023-06-12 09:42:37,positive\n
2,47857,6635,13640,1756517447067579904,1000253,664545,MashAllah boht hi acha aur orignal quality,[],5,Customer Service,NaN,1,2023-06-10 18:05:11,2023-06-12 09:42:39,positive\n
3,47858,6433,13311,1696567354689870080,1000253,667211,Nice and same as I ordered.,[],5,Delayed Delivery,NaN,1,2023-06-10 18:06:45,2023-06-12 09:42:40,positive\n
4,47859,6352,13178,5236553242660960256,1000253,664973,NaN,[],5,Customer Service,NaN,1,2023-06-10 18:07:58,2023-06-12 09:42:41,positive\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,47844,3986,11500,1199057130387849984,1000253,662407,NaN,[],5,Delayed Delivery,NaN,1,2023-06-10 14:24:45,2023-06-12 09:42:24,positive\n
9996,47848,4918,11676,3780070605557830144,1000240,656902,It was my first purchase from priceoye. I thin...,[],4,Delayed Delivery,NaN,1,2023-06-10 14:55:11,2023-06-12 11:31:41,neutral\n
9997,47849,5876,12220,2171268463370099968,1000253,664328,Every thing exceptional grading.,[],5,Packaging,NaN,1,2023-06-10 15:22:14,2023-06-12 09:42:31,positive\n
9998,47851,6197,12833,716973406596987008,1000253,664360,NaN,[],5,Product Price,NaN,1,2023-06-10 16:09:54,2023-06-12 09:42:32,positive\n
9999,47853,6203,13292,6081604072750999552,1000253,665195,NaN,[],5,Packaging,NaN,1,2023-06-10 16:21:10,2023-06-12 09:42:34,positive\n

**Address's Column Core Stuff**

Core_Strings = ['H','House', 'HOUSE', 'h', 'flat', 'Flat', 'room', 'Room', 'Block', 'block', 'shop', 'Shop', 'Plot', 'plot'
,'Street', 'st', 'street']

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   Product_id         10000 non-null  int64
 2   Product_flavor_id  10000 non-null  int64
 3   Shopper_id         10000 non-null  int64
 4   User_id            10000 non-null  int64
 5   Orderitem_id       10000 non-null  int64
 6   description        8052 non-null   object
 7   images             10000 non-null  object
 8   rating             10000 non-null  int64
 9   rating_reason      10000 non-null  object
 10  reply              0 non-null      float64
 11  status             10000 non-null  int64
 12  date_create        10000 non-null  datetime64[ns]
 13  date_modify        10000 non-null  datetime64[ns]
 14  LLM                10000 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(8), object(4)
memory usage: 1.1+ MB

In [4]:
data.describe()

,id,Product_id,Product_flavor_id,Shopper_id,User_id,Orderitem_id,rating,reply,status
count,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,10000.000000,10000.000000,0.0,10000.000000
mean,54930.697900,6047.520100,12855.759500,3.576568e+18,9.994661e+05,730149.496600,3.654300,NaN,0.654200
std,5497.874801,810.003053,1470.576736,2.372989e+18,2.828189e+04,121509.616649,1.702081,NaN,0.475652
min,47214.000000,12.000000,45.000000,1.000001e+09,3.000000e+00,63424.000000,1.000000,NaN,0.000000
25%,50988.000000,5798.000000,12331.000000,1.473240e+18,1.000234e+06,688035.250000,2.000000,NaN,0.000000
50%,53639.500000,6194.000000,12882.000000,3.562516e+18,1.000253e+06,726047.500000,5.000000,NaN,1.000000
75%,56484.250000,6568.000000,13737.000000,5.644401e+18,1.000268e+06,782217.500000,5.000000,NaN,1.000000
max,69636.000000,7504.000000,15862.000000,7.766278e+18,1.000563e+06,989906.000000,5.000000,NaN,1.000000

**Remove Duplicate Rows from Dataset**

In [5]:
data.drop_duplicates()
data

,id,Product_id,Product_flavor_id,Shopper_id,User_id,Orderitem_id,description,images,rating,rating_reason,reply,status,date_create,date_modify,LLM
0,47854,4504,10684,3583190052525640192,1000253,663560,The phone looks great. 10/10 quality. Delivere...,[],5,Delayed Delivery,NaN,1,2023-06-10 16:41:38,2023-06-12 09:42:35,positive\n
1,47856,5879,12207,1882191115889570048,1000253,664030,Thank you,[],5,Product Quality,NaN,1,2023-06-10 18:00:06,2023-06-12 09:42:37,positive\n
2,47857,6635,13640,1756517447067579904,1000253,664545,MashAllah boht hi acha aur orignal quality,[],5,Customer Service,NaN,1,2023-06-10 18:05:11,2023-06-12 09:42:39,positive\n
3,47858,6433,13311,1696567354689870080,1000253,667211,Nice and same as I ordered.,[],5,Delayed Delivery,NaN,1,2023-06-10 18:06:45,2023-06-12 09:42:40,positive\n
4,47859,6352,13178,5236553242660960256,1000253,664973,NaN,[],5,Customer Service,NaN,1,2023-06-10 18:07:58,2023-06-12 09:42:41,positive\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,47844,3986,11500,1199057130387849984,1000253,662407,NaN,[],5,Delayed Delivery,NaN,1,2023-06-10 14:24:45,2023-06-12 09:42:24,positive\n
9996,47848,4918,11676,3780070605557830144,1000240,656902,It was my first purchase from priceoye. I thin...,[],4,Delayed Delivery,NaN,1,2023-06-10 14:55:11,2023-06-12 11:31:41,neutral\n
9997,47849,5876,12220,2171268463370099968,1000253,664328,Every thing exceptional grading.,[],5,Packaging,NaN,1,2023-06-10 15:22:14,2023-06-12 09:42:31,positive\n
9998,47851,6197,12833,716973406596987008,1000253,664360,NaN,[],5,Product Price,NaN,1,2023-06-10 16:09:54,2023-06-12 09:42:32,positive\n
9999,47853,6203,13292,6081604072750999552,1000253,665195,NaN,[],5,Packaging,NaN,1,2023-06-10 16:21:10,2023-06-12 09:42:34,positive\n

**Positive Keywords , Negative Keywords and Feature Creation**

In [8]:
import pandas as pd
import regex as re
import numpy as np

# Assuming you have a DataFrame named 'data'

Positive_Strings = ['Alhumdulillah','Allhamdulliah', 'Alhamdulillah', 'Masha Allah','mashallah', 'Mashallah', 'MaShaAllah', 'Allah', 'Thank', 'thank', 'Thanks', 'Thank you', 'thank you',
                    'Behtareen','Behtereen', 'behtareen', 'awesome', 'Awesome', 'VIP', 'vip', 'Vip', 'Best', 'Good', 'best', 'good product','Good packing', 'nyc', 'nice', 'Nice', 'Allaw', 'allaw',
                    'orginal product', 'thnx','Orignal', 'Acha product', 'Best', 'ZabbarDast', 'Zabrdast', 'zabrdast', 'Zbrdast', 'Satisfactory', 'satisfactory', 'satisfied', 'Satisfied', 'Satisfies',
                    'satisfying','Not bad','shukiya','acchi hai','Outstanding','keep it up','Aala product','geniue',
                    'Bhut he Aala', 'happy', 'Happy', '#Trusted', '#trusted', 'Trusted', 'perfect', 'Perfect', 'Excellent', 'appreciated', 'Highly recommend', 'Amazing', 'glad', 'Outstanding', 'Bhot khoob',
                    'Nice product',
                    'Zbardast', 'Recommended.', 'Genuine', 'pretty good', 'high quality', 'Product original', 'Product is original']


Negative_Strings = ['Bad', 'bad', 'Ghatya', 'ghatya', 'Fruad', 'fraud', 'bakwas', 'Bakwas', 'poor', 'Poor', 'missing', 'cheap', 'Cheap', 'not satisfied', 'not recommended', '3rd class',
                    'Not recommended', 'not good', 'local quality']


# Conditions
conditions_accepted = (((data['LLM'].str.contains('Positive|positive', case=False)) &
    (data['rating'].astype(str).str.contains('4|5')) &
    (~data['description'].isna()))|
                       (data['LLM'].str.contains('neutral|Neutral', case=False) &
                        data['rating'].astype(str).str.contains('4|5') &
                        data['description'].astype(str).str.contains('|'.join(Positive_Strings), case=False)&(~data['description'].isna()))|
                       (data['LLM'].str.contains('Neutral|neutral', case=False) &
                                  data['rating'].astype(str).str.contains('1|2|3') &
                                  data['description'].astype(str).str.contains('|'.join(Positive_Strings), case=False))|
                       (data['LLM'].str.contains('negative|Negative', case=False) &
                                  data['rating'].astype(str).str.contains('4|5') &
                                  data['description'].astype(str).str.contains('|'.join(Positive_Strings), case=False))|
                       (data['LLM'].str.contains('Positive|positive', case=False) &
                                  data['rating'].astype(str).str.contains('3')&
                        (~data['description'].isna())|(data['description'].astype(str).str.contains('|'.join(Positive_Strings), case=False)))|
                       (data['LLM'].str.contains('Positive|positive', case=False) &
                                  data['rating'].astype(str).str.contains('1|2') &
                                  data['description'].astype(str).str.contains('|'.join(Positive_Strings), case=False)

                    ))

conditions_rejected = ((data['LLM'].str.contains('Negative|negative', case=False) &
                        data['rating'].astype(str).str.contains('1|2|3')) |
                       (data['LLM'].str.contains('neutral|Neutral', case=False) &
                        data['rating'].astype(str).str.contains('1|2') &
                        data['description'].astype(str).str.contains('|'.join(Negative_Strings), case=False)) |
                       (data['LLM'].str.contains('Negative|negative', case=False) &
                        data['rating'].astype(str).str.contains('4|5') &
                        data['description'].astype(str).str.contains('|'.join(Negative_Strings), case=False))|
                       (data['LLM'].str.contains('Positive|positive', case=False) &
                                  data['rating'].astype(str).str.contains('1|2') &
                                  data['description'].astype(str).str.contains('|'.join(Negative_Strings), case=False))|
                       (data['LLM'].str.contains('Neutral|neutral', case=False) &
                                  data['rating'].astype(str).str.contains('1|2|3') &
                                  data['description'].astype(str).str.contains('|'.join(Negative_Strings), case=False))

                       )

conditions_ignore = ~conditions_accepted & ~conditions_rejected

# Applying labels based on conditions
data['Labeled Result'] = np.select([conditions_accepted, conditions_rejected, conditions_ignore],
                                   ['accepted', 'rejected', 'ignore'],
                                   default='ignore')

# Display the resulting DataFrame
#data.to_excel('Labled_Data.xlsx', index =False)
data

**Convert Labled data into Excel Format**

In [ ]:
# Display the resulting DataFrame
data.to_excel('Labled_Data.xlsx', index =False)